export default {
    iconMenu: Object.freeze([
        'el-icon-menu',
        'el-icon-document',
        'el-icon-box',
        'el-icon-user',
        'el-icon-setting',
        'el-icon-bank-card',
        'el-icon-s-data',
        'el-icon-bell',

        'aicon icon-yejianx',
        'aicon icon-quyu-',
        'aicon icon-CDN',
        'aicon icon-CDN2',
        'aicon icon-toggle',
        'aicon icon-zonglan',
        'aicon icon-zonglan2',
        'aicon icon-quanping3',
        'aicon icon-xinbaniconshangchuan-',
        'aicon icon-quanping2',
        'aicon icon-bangzhu3',
        'aicon icon-shouye1',
        'aicon icon-shouye',
        'aicon icon-bangzhuzhongxin',
        'aicon icon-shenhe',
        'aicon icon-xianlu',
        'aicon icon-wangluo',
        'aicon icon-rizhi',
        'aicon icon-tongji',
        'aicon icon-APIguanli',
        'aicon icon-jiedian',
        'aicon icon-jiance1',
        'aicon icon-baobiao',
        'aicon icon-shenhe',
        'aicon icon-WAF',
        'aicon icon-zhuanfa1',
        'aicon icon-shouquan1',
        'aicon icon-yanzhengma2'
    ])
}
